name: Thank Contributor

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Thank Contributor
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue = context.payload.issue;
          const issueCreator = issue.user.login;
          const issueNumber = issue.number;
          const message = `Thank you, @${issueCreator}, for creating issue #${issueNumber}! We appreciate your contribution.`;
          const comment = await github.issues.createComment({
            issue_number: issueNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
